# .yamllint.yml
# Custom linting rules: Increase max line length for readability, enforce 2-space indentation, and disallow trailing spaces.
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces:
    level: error
